// Generated by @nuxtjs/sitemap
/// <reference path="./nuxt-sitemap-virtual.d.ts" />
import type { SitemapUrl, SitemapItemDefaults, SitemapIndexRenderCtx, SitemapInputCtx, SitemapRenderCtx, SitemapOutputHookCtx, SitemapSourcesHookCtx } from '@nuxtjs/sitemap'

declare module 'nitropack' {
  interface PrerenderRoute {
    _sitemap?: SitemapUrl
  }
  interface NitroRouteRules {
    index?: boolean
    sitemap?: SitemapItemDefaults | false
  }
  interface NitroRouteConfig {
    index?: boolean
    sitemap?: SitemapItemDefaults | false
  }
  interface NitroRuntimeHooks {
    'sitemap:index-resolved': (ctx: SitemapIndexRenderCtx) => void | Promise<void>
    'sitemap:input': (ctx: SitemapInputCtx) => void | Promise<void>
    'sitemap:resolved': (ctx: SitemapRenderCtx) => void | Promise<void>
    'sitemap:output': (ctx: SitemapOutputHookCtx) => void | Promise<void>
    'sitemap:sources': (ctx: SitemapSourcesHookCtx) => void | Promise<void>
  }
}

declare module 'nitropack/types' {
  interface PrerenderRoute {
    _sitemap?: SitemapUrl
  }
  interface NitroRouteRules {
    index?: boolean
    sitemap?: SitemapItemDefaults | false
  }
  interface NitroRouteConfig {
    index?: boolean
    sitemap?: SitemapItemDefaults | false
  }
  interface NitroRuntimeHooks {
    'sitemap:index-resolved': (ctx: SitemapIndexRenderCtx) => void | Promise<void>
    'sitemap:input': (ctx: SitemapInputCtx) => void | Promise<void>
    'sitemap:resolved': (ctx: SitemapRenderCtx) => void | Promise<void>
    'sitemap:output': (ctx: SitemapOutputHookCtx) => void | Promise<void>
    'sitemap:sources': (ctx: SitemapSourcesHookCtx) => void | Promise<void>
  }
}

declare module 'vue-router' {
  interface RouteMeta {
    sitemap?: SitemapItemDefaults | false
  }
}

declare module '#app' {
  interface PageMeta {
    sitemap?: SitemapItemDefaults | false
  }
}

declare module 'nuxt/app' {
  interface PageMeta {
    sitemap?: SitemapItemDefaults | false
  }
}

export {}
